/*
 * This file is generated by jOOQ.
 */
package net.redpipe.example.wiki.keycloakJooq.jooq;


import javax.annotation.Generated;

import net.redpipe.example.wiki.keycloakJooq.jooq.tables.Pages;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PAGES_NAME_KEY = Indexes0.PAGES_NAME_KEY;
    public static final Index PAGES_PKEY = Indexes0.PAGES_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PAGES_NAME_KEY = Internal.createIndex("pages_name_key", Pages.PAGES, new OrderField[] { Pages.PAGES.NAME }, true);
        public static Index PAGES_PKEY = Internal.createIndex("pages_pkey", Pages.PAGES, new OrderField[] { Pages.PAGES.ID }, true);
    }
}
