/*
 * This file is generated by jOOQ.
*/
package net.redpipe.example.wiki.keycloakJooq.jooq;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import net.redpipe.example.wiki.keycloakJooq.jooq.tables.Pages;
import net.redpipe.example.wiki.keycloakJooq.jooq.tables.records.PagesRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PagesRecord, Integer> IDENTITY_PAGES = Identities0.IDENTITY_PAGES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PagesRecord> PAGES_PKEY = UniqueKeys0.PAGES_PKEY;
    public static final UniqueKey<PagesRecord> PAGES_NAME_KEY = UniqueKeys0.PAGES_NAME_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PagesRecord, Integer> IDENTITY_PAGES = createIdentity(Pages.PAGES, Pages.PAGES.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PagesRecord> PAGES_PKEY = createUniqueKey(Pages.PAGES, "pages_pkey", Pages.PAGES.ID);
        public static final UniqueKey<PagesRecord> PAGES_NAME_KEY = createUniqueKey(Pages.PAGES, "pages_name_key", Pages.PAGES.NAME);
    }
}
