/*
 * This file is generated by jOOQ.
 */
package net.redpipe.example.wiki.keycloakJooq.jooq;


import javax.annotation.Generated;

import net.redpipe.example.wiki.keycloakJooq.jooq.tables.Pages;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.pages</code>.
     */
    public static final Pages PAGES = net.redpipe.example.wiki.keycloakJooq.jooq.tables.Pages.PAGES;
}
