/*
 * This file is generated by jOOQ.
*/
package org.vertxrs.example.wiki.keycloakJooq.jooq.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.vertxrs.example.wiki.keycloakJooq.jooq.Keys;
import org.vertxrs.example.wiki.keycloakJooq.jooq.Public;
import org.vertxrs.example.wiki.keycloakJooq.jooq.tables.records.PagesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pages extends TableImpl<PagesRecord> {

    private static final long serialVersionUID = 1983252823;

    /**
     * The reference instance of <code>public.pages</code>
     */
    public static final Pages PAGES = new Pages();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PagesRecord> getRecordType() {
        return PagesRecord.class;
    }

    /**
     * The column <code>public.pages.id</code>.
     */
    public final TableField<PagesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('pages_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.pages.name</code>.
     */
    public final TableField<PagesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>public.pages.content</code>.
     */
    public final TableField<PagesRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.pages</code> table reference
     */
    public Pages() {
        this("pages", null);
    }

    /**
     * Create an aliased <code>public.pages</code> table reference
     */
    public Pages(String alias) {
        this(alias, PAGES);
    }

    private Pages(String alias, Table<PagesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Pages(String alias, Table<PagesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PagesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PAGES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PagesRecord> getPrimaryKey() {
        return Keys.PAGES_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PagesRecord>> getKeys() {
        return Arrays.<UniqueKey<PagesRecord>>asList(Keys.PAGES_PKEY, Keys.PAGES_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Pages as(String alias) {
        return new Pages(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pages rename(String name) {
        return new Pages(name, null);
    }
}
